### ISSUE TITLE
Script/command to write resolved catalog profile to a JSON file

### ISSUE THREAD

**Issue by vikas-agarwal76** [IBM/compliance-trestle#1188] opened 2022-09-23 05:29 UTC
## Issue description / feature objectives
We need the resolved catalog/profile to be written to a file for use by SCC so that they don't need to get a profile and then related catalogs and then merge the content.

**Comment by fsuits** [comment] 2022-09-26 00:27
Duplicate of #1110 to make a CLI command to generate a json resolved profile catalog.

@vikas-agarwal76  But if SCC makes use of the trestle sdk they can create the resolved profile catalog directly from the profile - in memory - and/or save it to file.  Do they actually need a CLI command for this?

Here is the existing command in `profile_resolver.py`:
```class ProfileResolver():
    """Class to resolve a catalog given a profile."""

    @staticmethod
    def get_resolved_profile_catalog(
        trestle_root: pathlib.Path,
        profile_path: str,
        block_adds: bool = False,
        block_params: bool = False,
        params_format: Optional[str] = None,
        param_rep: ParameterRep = ParameterRep.VALUE_OR_LABEL_OR_CHOICES,
        show_value_warnings: bool = False
    ) -> cat.Catalog:
        """
        Create the resolved profile catalog given a profile path.

        Args:
            trestle_root: root directory of the trestle project
            profile_path: string path or uri of the profile being resolved
            block_adds: prevent the application of adds in the final profile
            block_params: prevent the application of setparams in the final profile
            params_format: optional pattern with dot to wrap the param string, where dot represents the param string
            param_rep: desired way to convert params to strings
            show_value_warnings: warn if prose references a value that has not been set

        Returns:
            The resolved profile catalog
        """
```

**Comment by vikas-agarwal76** [comment] 2022-09-26 01:10
@fsuits SCC will only import one file (profile) from the repo. To resolve the profile, they will need all the  imported catalogs also. Hence, for this we need to generate the resolved catalog profile in test-profiles repo, which they can just pull from the repo and use.

Hence, you can just create a script that takes the profile and create resolved catalog profile. We will then add this script as part of the automation to generate it whenever a new profile is assembled.

**Closed** 2022-09-29 02:59 UTC
