### ISSUE TITLE
trestle author command fails to create output when optional arguments are not provided

### ISSUE THREAD

**Issue by mrgadgil** [IBM/compliance-trestle#1342] opened 2023-04-04 18:15 UTC
## Describe the bug

Command executed: `author jinja -i ens_ssp_out.md.jinja -o ENS_ssp.md -v`
Expected output: Trestle should generate SSP using the jinja template

Actual output: Trestle does not return an error or generate an output
When using verbose this is the behavior

sh-4.4# trestle author jinja -i ens_ssp_out.md.jinja -o ENS_ssp.md -v
trestle.core.commands.author.jinja:112 DEBUG: Starting jinja command

If I provide dummy spp and profile arguments, then trestle command proceeds.

## To Reproduce

Run this command
trestle author jinja -i ens_ssp_out.md.jinja -o ENS_ssp.md -v

## Expected behavior

Likely fix:
Introduce a default return statement when ssp and profile are not provided

https://github.com/IBM/compliance-trestle/blob/develop/trestle/core/commands/author/jinja.py#L151

```
return JinjaCmd.jinja_multiple_md(
                    pathlib.Path(args.trestle_root),
                    input_path,
                    output_path,
                    lut,
                    parameters_formatting=args.bracket_format,
                    value_assigned_prefix=args.value_assigned_prefix,
                    value_not_assigned_prefix=args.value_not_assigned_prefix
                )
```

## Environment

- OS: \[e.g. iOS\] ubi minimal
- Python version: Python 3.9.13
- Installed packages: 2.0.0

**Comment by enikonovad** [comment] 2023-04-05 04:05
@mrgadgil I am not sure what is the use case of not providing the ssp or profile to Jinja command?

Jinja in Trestle context is used to either:
1. Generate control docs and thus require a profile to be provided
2. Generate markdown ssp and thus require a ssp and profile to be provided

If nothing of this is provided there is nothing to generate, so program quits. I can only raise an exception in this case as it is unclear what to do.

Could you please share the contents of `ens_ssp_out.md.jinja` to understand the use case?

**Comment by mrgadgil** [comment] 2023-04-05 13:23
@enikonovad 
I am using the trestle author command to generate ENS SSP. The ENS SSP is not control by control based. I will ping you on slack to share the contents of the ens_ssp_out.md.jinja

**Comment by vikas-agarwal76** [comment] 2023-04-19 05:13
closing as the issue is resolved

**Closed by vikas-agarwal76** 2023-04-19 05:13 UTC
