### ISSUE TITLE
Check for split-too-fine is temporarily disabled.  Make sure it is re-enabled

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#576] opened 2021-06-22 05:09 UTC
Changes to oscal 1.0.0 made it hard to check element paths properly to know if a requested split is too fine.  The check and tests have been temporarily disabled.  Make sure to re-enable them when possible.

**Comment by butler54** [comment] 2021-07-06 22:53
Duplicate of #422 closing.

**Closed by butler54** 2021-07-06 22:53 UTC
Labels: bug, duplicate
