### ISSUE TITLE
Remove -f option of split command and automatically infer the base model to be split

### ISSUE THREAD

**Issue by vikas-agarwal76** [IBM/compliance-trestle#603] opened 2021-06-29 07:06 UTC
Currently split command requires -f option to specify the base (sub)-model file to be split. The split command should be changed to not require -f option and it should be smart enough to figure out which json/yaml files contain the elements to be split. For this the elements have to specified in full rather than relative to current directory / file to be split. 

For example, -e 'catalog.metadata.*' rather than -f metadata.json -e 'metadata.*' 

Refactor the split code have a function that takes the full element and performs the split.

**Comment by butler54** [comment] 2021-07-07 04:52
Duplicate of #410 closing.

**Closed by butler54** 2021-07-07 04:52 UTC
